<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="PandarQT_LiDAR">
  <xacro:property name="PI" value="3.1415926535897931" />
  <xacro:macro name="PandarQT" params="link:=base_link topic:=PandarQT_Data hz:=10 lasers:=64 samples:=2187 min_range:=0.1 max_range:=30.0 min_angle_h:=-180 max_angle_h:=180 min_angle_v:=-52.1 max_angle_v:=52.1 resolution:=0.02 noise:=0.008 visual:=true gpu:=false">

    <!-- Gazebo requires the velodyne_gazebo_plugins package -->
    <gazebo reference="${link}">
      <xacro:if value="${gpu}">
        <sensor type="gpu_ray" name="${link}_Sensor">
          <pose>0 0 0 0 0 0</pose>
          <visualize>${visual}</visualize>
          <update_rate>${hz}</update_rate>
          <ray>
            <scan>
              <horizontal>
                <samples>${samples}</samples>
                <resolution>1</resolution>
                <xacro:if value="${max_angle_h-min_angle_h-360.0}">
                    <min_angle>${min_angle_h/180.0*PI}</min_angle>
                    <max_angle>${max_angle_h/180.0*PI}</max_angle>
                </xacro:if>
                <xacro:unless value="${max_angle_h-min_angle_h-360.0}">
                    <min_angle>${min_angle_h/180.0*PI}</min_angle>
                    <max_angle>${(min_angle_h+(max_angle_h-min_angle_h)*(samples-1)/samples)/180.0*PI}</max_angle>
                </xacro:unless>
              </horizontal>
              <vertical>
                <samples>${lasers}</samples>
                <resolution>1</resolution>
                <min_angle>${min_angle_v/180.0*PI}</min_angle>
                <max_angle>${max_angle_v/180.0*PI}</max_angle>
              </vertical>
            </scan>
            <range>
              <min>${min_range}</min>
              <max>${max_range}</max>
              <resolution>${resolution}</resolution>
            </range>
            <noise>
              <type>gaussian</type>
              <mean>0.0</mean>
              <stddev>0.0</stddev>
            </noise>
          </ray>
          <plugin name="LidarPubData" filename="$(find mars_rover)/plugins/LidarPubData/build/libLidarPubData.so">
            <topicName>${topic}</topicName>
            <frameName>${link}</frameName>
            <min_range>${min_range}</min_range>
            <max_range>${max_range}</max_range>
            <gaussianNoise>${noise}</gaussianNoise>
            <min_intensity>0</min_intensity>
          </plugin>
        </sensor>
      </xacro:if>
      <xacro:unless value="${gpu}">
        <sensor type="ray" name="${link}_Sensor">
          <pose>0 0 0 0 0 0</pose>
          <visualize>${visual}</visualize>
          <update_rate>${hz}</update_rate>
          <ray>
            <scan>
              <horizontal>
                <samples>${samples}</samples>
                <resolution>1</resolution>
                <xacro:if value="${max_angle_h-min_angle_h-360.0}">
                    <min_angle>${min_angle_h/180.0*PI}</min_angle>
                    <max_angle>${max_angle_h/180.0*PI}</max_angle>
                </xacro:if>
                <xacro:unless value="${max_angle_h-min_angle_h-360.0}">
                    <min_angle>${min_angle_h/180.0*PI}</min_angle>
                    <max_angle>${(min_angle_h+(max_angle_h-min_angle_h)*(samples-1)/samples)/180.0*PI}</max_angle>
                </xacro:unless>
              </horizontal>
              <vertical>
                <samples>${lasers}</samples>
                <resolution>1</resolution>
                <min_angle>${min_angle_v/180.0*PI}</min_angle>
                <max_angle>${max_angle_v/180.0*PI}</max_angle>
              </vertical>
            </scan>
            <range>
              <min>${min_range}</min>
              <max>${max_range}</max>
              <resolution>${resolution}</resolution>
            </range>
            <noise>
              <type>gaussian</type>
              <mean>0.0</mean>
              <stddev>0.0</stddev>
            </noise>
          </ray>
          <plugin name="LidarPubData" filename="$(find mars_rover)/plugins/LidarPubData/build/libLidarPubData.so">
            <topicName>${topic}</topicName>
            <frameName>${link}</frameName>
            <min_range>${min_range}</min_range>
            <max_range>${max_range}</max_range>
            <gaussianNoise>${noise}</gaussianNoise>
            <min_intensity>0</min_intensity>
          </plugin>
        </sensor>
      </xacro:unless>
    </gazebo>
  </xacro:macro>
</robot>
